---
# ##################################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 015 - now when aptitude has been installed, update the packages
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-28
# version? likely around 0.7
# ##################################################################
#
- hosts: hamradio
  tasks:
    - ping: ~
    - name: Update APT cache
      become: true
      become_method: su
      become_user: root
      apt:
        update_cache: yes
#
    - name: Upgrade installed packages
      become: true
      become_method: su
      become_user: root
      apt:
        upgrade: safe
...
