---
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 02 - now when aptitude has been installed, update the packages
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-27
# version? probably 0.7 or something
#
- hosts: hamradio
  tasks:
    - ping: ~
    - name: Update APT package manager repositories cache
      become: true
      become_method: su
      become_user: root
      apt:
        update_cache: yes
#
    - name: Upgrade installed packages
      become: true
      become_method: su
      become_user: root
      apt:
        upgrade: safe
...
