---
# #######################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 031 - install the required for SDR work packages
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-28
# version? likely around 0.7
# WARNING: my SDR's are 2x SDRPlay and 1x RTL-SDR
# I do not know how to install software for YOUR SDRs.
# #######################################################
#
- hosts: hamradio
  tasks:
  - name: apt multi-install with_items avahi-daemon / libavahi-client-dev / doxygen / swig / pexpect
    become: true
    become_method: su
    become_user: root
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - 'python' # openWebRX needs this.
# And (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (missing: PYTHON3_LIBRARIES PYTHON3_INCLUDE_DIRS)
      - 'avahi-daemon' # or SoapyRemote shall yell
      - 'libavahi-client-dev' # ditto
      - 'doxygen' # or SoapySDR shall complain slightly
      - 'swig' # or SoapySDR shall complain slightly
      - 'python-pexpect' # or expext-send dialogues in Ansible will fail
...
