---
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 04 - install the required packages
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-27
# version? probably 0.7 or something
#
- hosts: hamradio
  tasks:
  - name: apt multi-install with_items avahi-daemon / libavahi-client-dev / doxygen / swig / pexpect
    become: true
    become_method: su
    become_user: root
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - 'python' # openWebRX needs this.
# And (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (missing: PYTHON3_LIBRARIES PYTHON3_INCLUDE_DIRS)
      - 'avahi-daemon' # or SoapyRemote shall yell
      - 'libavahi-client-dev' # ditto
      - 'doxygen' # or SoapySDR shall complain slightly
      - 'swig' # or SoapySDR shall complain slightly
      - 'python-pexpect' # or expext-send dialogues in Ansible will fail
...

