---
# #####################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 045 - manipulate become_user=sudo back to sudo
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-28
# version? likely around 0.7
# #####################################################
#

- hosts: local
  connection: local
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: verify the value of become_method before changing it
      command: grep become_method /home/n0ne/Ansible/ansible.cfg
      register: become_variant
#
    - debug: msg="{{ become_variant.stdout }} "
#
    - name: make a trick
      shell: sed -i "s/^become_method = sudo/become_method = su/g" /home/n0ne/Ansible/ansible.cfg
#
    - name: verify what we just did
      command: grep become_method /home/n0ne/Ansible/ansible.cfg
      register: become_variant
#
    - debug: msg="{{ become_variant.stdout }} "
...
