---
# ################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 046 - seinstall sudo package on target host
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-28
# version? likely around 0.7
#
# ################################################
#
- hosts: hamradio
  tasks:
   - name: apt remove sudo # Back to non-Ubuntu world
     become: true
     become_method: su
     become_user: root
     apt:
       name: sudo
       state: absent # Before we continue on Debian
...
