---
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 05 - Manipulate the git directory
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-27
# version? probably 0.7 or something
#
- hosts: hamradio
  vars:
    git_basedir: "/home/shaitan/GIT"
  tasks:
  - stat:
      path: "{{ git_basedir }}"
    register: git_dir
  - name: Back up the old git dir
    command: mv "{{ git_basedir }}" "{{ git_basedir }}-BACK-{{ ansible_date_time.iso8601 }}"
    when: git_dir.stat.exists
  - name: Create a new directory for the git
    file:
      path: "{{ git_basedir }}" # 
      state: directory
...

