---
# ########################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 057 - Restart for full providence
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-29
# version? likely around 0.7
# ########################################################
#
- hosts: hamradio
  tasks:
    - name: Queue a reboot that starts in +1 min
      become: yes
      become_method: su
      become_user: root
      command: "/sbin/shutdown --reboot +1"
      async: 0 # must be 0 not 1 or weird problems
      poll: 0
      ignore_errors: true
#
    - name: Wait 180 secs before confirming the rebirth
      pause:
        minutes: 3
#
    - name: See it with own eyes
      command: 'uptime'
      register: time_up
#
    - debug: msg="{{ time_up.stdout }}"
...
