---
# ########################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 061 - enumerate connected SDRs "locally" (at air1)
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-29
# version? likely around 0.7
# ########################################################
#
- hosts: air1
  tasks:

    - name: A modest task to enumerate RTL-SDR via rtl_test
      become: yes
      become_method: su
      become_user: root
      command: 'rtl_test -t'
      register: rtls_found_locally
      ignore_errors: true
#
    - debug: msg="{{ rtls_found_locally.stdout }}"

    - name: enumerate SDRs connected to the radio host
      become: yes
      become_method: su
      become_user: root
      command: 'SoapySDRUtil --find'
      register: soapys_found_locally
      ignore_errors: true
#
    - debug: msg="{{ soapys_found_locally.stdout }}"
...

