---
# ########################################################
# Ansible playbook for a SDRPlay+OpenWebRx listening post
# part 063 - enumerate connected SDRs "remotely" (at webhost)
#
# (origin and copyleft) - es1lau
# last modified - 2019-07-29
# version? likely around 0.7
# ########################################################
#
# NB! an IP based request keeps in cache some time (1min?).
# This while the driver based requests are possible.
#
- hosts: air3
  vars:
    air1_ip: "10.10.117.117"
  tasks:
    - name: enumerate SDRPlays accessible via Soapy channel
      become: yes
      become_method: su
      become_user: root
      command: 'SoapySDRUtil --find="remote={{ air1_ip }}"'
      register: ip_questioned_remotely
      ignore_errors: true
#
    - debug: msg="{{ ip_questioned_remotely.stdout_lines }}"
#
    - name: sleep 8 sec while the cache populates
      command: 'sleep 8'

    - name: enumerate SDRPlays accessible via Soapy channel
      become: yes
      become_method: su
      become_user: root
      command: 'SoapySDRUtil --find="remote:driver = sdrplay"'
      register: soapys_found_remotely
      ignore_errors: true
#
    - debug: msg="{{ soapys_found_remotely.stdout_lines }}"
#
    - name: enumerate RTL-SDRs accessible via Soapy channel
      become: yes
      become_method: su
      become_user: root
      command: 'SoapySDRUtil --find="remote:driver = rtlsdr"'
      register: rtls_found_remotely
      ignore_errors: true
#
    - debug: msg="{{ rtls_found_remotely.stdout_lines }}"
...
